#+OPTIONS: \n:t ^:nil

* 文章を書く練習をする場
** 000_文章を書く練習を始めます、という宣言


　率直に言うと、今私は小説を書きあぐねている。

「小説を書きあぐねる」

という言葉を使うと、小説指南本を読み漁っている人はある一冊の本を思いつくかもしれない。

『書きあぐねている人のための小説入門』

　私はこの本をたぶん十回以上読み返している。それにも関わらず、私は依然として小説を書きあぐねている。少し前までは、ギリギリまで待ってもらってなんとか完成させるという形で小説を書き上げることが多かったのだが、最近は体力が落ちたのか、書けなくなったときに気合いで徹夜でとにかく書き上げるという最終手段が使えなくなってしまった。元々、筆が速いほうではなかった。二次創作の時から、半年に一作くらいかけたらいいほうかなという程度の速度でしかなく、それは一次創作を始めてからも、サークル活動を始めてからも変わらなかった。

　小説を書いている人たちは、小説を書くことを楽しいと感じているのだろうか。私は九割苦しんでいる。というのも、ずっと悩みながら書き続けて、やっと書きたいことが見つかって一気に筆が進む瞬間があるのだが、そのときだけは本当に気持ちがいい。脳内麻薬という言葉は比喩として正しいのだなと感じる。もちろん麻薬をやったことは無いですが……。音楽家などが薬に手を出してしまう気持ちも、少し分かってしまうような気がする。

　ある一定のクオリティのものを作るというのは、いつも事前の想定の数十倍くらい苦しい作業になる。不思議なことにやめたいと感じることはないのだが、今直面しているこの原稿からはもう手を引きたいと思ってしまうことは本当に頻繁にある。というより毎回それは思っている。その後奇跡的に書きたいことを見つけられるか、見つけられないかという運に頼ることになってしまっている。

　一応私は、小説を書くことを生涯の自分の活動にしたいと思って取り組んでいるし、やるからには何か賞を取りたいと思っているし、読んだ人に何らかの影響を与えられたらいいなと思っている。一人のアマチュアとしてそれくらいの野望は持っている。だがそれをやりとげる、というよりそこにいたるまでに継続するための体力や精神力が絶望的に足りていない。そのことをここ一年くらいで痛感している。

　私は書きあぐねてしまうと文章指南本・小説指南本を読みあさる癖がある。これまでに読んできたものを振り返ると、


『書きあぐねている人のための小説入門』

『工学的ストーリー創作入門』

『スクリプトドクターの脚本教室・初級編』

『スクリプトドクターの脚本教室・中級編』

『文章表現　400字からのレッスン』

『新人小説賞の傾向と対策』

『書く人はここで躓く！』

『マナーはいらない　小説の書き方講座』


　最近まで（そして今も）原稿と格闘しているのだが、部屋を見まわしただけでもこれくらいの文章指南本が見つかった。他にも何冊か段ボールの中に隠れいている本がある。（これは埋もれているわけでなく、わざわざ本棚を買ってそこに入れなくても、段ボールの中にしまったり取り出したりすれば何の不便も無いと思ってそうしているだけだ。決して整理整頓ができないわけではない）


＜1280文字。ここまで一息で書いた。ここで集中力は途切れた。＞


　しばらく時間をあけてからまた書き始めた。自分が何を書こうとしていたのかはきれいさっぱり忘れてしまっている。正確には、書こうとしていたこと自体は分かる。

　しかしそのときの情動を過去に置き去りにしてしまっている。


＿＿＿＿＿

＜書こうと思っていた内容＞

　文章指南の本を買い漁り、読み漁るほど悩んでいるのに小説が書けない。最近新しく読んだ文章指南本である『原稿用紙10枚を書く力』に、質を上げたいならまずは量をこなすしかない。マラソンのフルコースを走ったことがなく、ただ筋トレだけをしている人は絶対にマラソン選手にはなれない。400字がどういうものなのか。2000、4000字を何度も書き、この文字数を書くときに自分はどれくらいの時間がかかるのか、どのくらい疲れるのかを性格に把握しておくことが重要だ、ということをこの本から学び、ならばまずは文字数をひたすら増やすだけの練習をしてみようじゃないかとこの文章を書き始めた……

＿＿＿＿＿


　といった内容の文章を書こうと思っていた。思っていたのだ。

　しかしその文書を書こうと思っていた時の勢いがもうなくなってしまったから、上記のあらすじを膨らませて読める文章にするという気力がもうない。いつもこうなってしまって、時々思い立っては小説やエッセイを書いてみはするものの何も完成させられずに、もう二度と開かれることのないテキストファイルが1つ増えるのだった。


　文章を書くに当たっての呪いがある。構成の呪いと、文章の呪いだ。構成の呪いとは、文章を書きながら（そろそろ起承転結の起が終わる頃だな……結は決まってるけど転はまだ決まっていないのにこのまま書いて大丈夫だろうか……。もう少しプロットを練り直してみようかな）そんなことを考えているうちに筆が止まって、自分が今書いている文章が最悪の出来だと感じて全部消してしまいたくなる、そんな状態のことだ。

　文章の呪いとは単純に、あらすじは決まっているのにそれを肉付けしようとして文章を書こうとしても、まったく魅力的だと思える文章が思いつかず、あらすじに書いた文章をそのまま繰り返すだけになってしまう状態のことだ。

　この二つの呪いがあるから、文章を書けるときは構成の呪いに足を引っ張られ、構成が思いつくときには文章の呪いに道を塞がれてしまう。

「何をそんなに悩んでいるのか。それが人様に提出する原稿だったとして、完成させられない方が迷惑をかける可能性が高いのだし、不完全な原稿を出しても校正者や読者に怒られるのは自分だけだが、原稿が遅れに遅れたり完成させられなかったりして迷惑を被るのは原稿を受け取る側の人間なのだから、そんなことを言っていられる立場ではないだろう」

　というのが一般常識的な意見だと思う。私も頭の中では分かっているのだが、あまりにドツボにはまり込むと、もはや「苦し紛れで提出する」ことができるような原稿すら完成させられなくなってしまう。小説を書き、他の人の小説を読み、という活動をすればするほど、自分の中の呪いが強くなってしまい、執筆の手を絡め取っていく。


　そんなこんなで、文章を書く練習をすることにした。文章を完成させる練習ではない。ぎりぎり完成品だとは自分で思えない文章でも、人の目に触れるところに投稿する。まったく文字数が稼げなくても投稿する。構成もなっていない、文章もただの箇条書きみたいな文章になってしまったとしてもとにかく人の目に触れるところに出す。

　そういう練習をすることにする。

　投稿場所の候補としては、カクヨム・note・GitHubなどがあるが、noteは自分の投稿がすべてフォロワーさんに見えてしまうので、クオリティが全く補償できない文章を投稿するのは後ろめたい。GitHubはその点誰にも通知が行かないからやりやすいのだが、読もうとした人が読みやすい媒体ではない。というわけで、作品を新しく書き始めたときにだけ通知が行き、それ以降の更新は作品をフォローしていなければ通知されないカクヨムが最も自分の投稿目的に合っているということがわかったので、これからカクヨムで文章の練習をしていくことにする。

　既に更新が止まってしまったエッセイを横目で見ながら……。


＜3050文字＞

＜ここまで書いて力尽きた。原稿用紙10枚は4000字。まだまだ道のりは遠い＞
** 001_書けなくなりました


　普段、文章が全く書けなくて苦しんでいる自分が、奇跡的に1日で3000字書くことができた。こんなにうまくいったことはないと、大喜びしてこれからも頑張ろうと思っていたのですが、文章を書くために昂ぶってしまった神経が元に戻らず、昨日は一睡もできなかった。

　なので会社から帰ってきて、ついさっきまで爆睡していた。そして文章のネタは何も無い。こうして現状を書き連ねているだけだ。2日目にしてこの体たらくである。一体何をやっているのだという感じだが、この作品ではこういう「文章にもなりきれていない文章」を投稿しながら、自分自身のハードルを下げていき、あわよくば読んだ人の中のハードルも下がって、皆が今より少し幸せになったらいいなと思っている。


＜315文字＞
** 002_弁証法の紹介[否定の否定]　平和に関する高校生の発言への批判について
  少し前、ある日本人高校生の発言を巡ってツイッターがざわついていた。ざわついていたなんて言い方はあまり正確な表現ではなくて、その高校生に対する否定的な意見や、その高校生の姿を捕まえて、だから今の日本の教育は駄目なのだと糾弾する意見であふれていた。
　特に引用リツイートは酷かったと思う。引用リツイートには人間を攻撃的にする作用が含まれているから、使うときは最大限自省してから使うことをおすすめする。空リプの方が闇が深い？　それは確かにそう。我々も気をつけよう。

　ここでは私が好きな「弁証法」という思考法について紹介したい。

　人間の思考法は主に３つある。演繹法、帰納法、弁証法である。演繹は、AだからB、BだからC……だからAだからCである、という「論理的に考えなさい」と言われて真っ先に思いつくものである。
　帰納法とは「このカラス1は黒い。このカラス2は黒い……このカラス999は黒い。ならばカラスは黒い。」と材料をたくさん積み上げる方法である。数学以外では、帰納法は演繹法に比べて、必ず根拠から理論への飛躍を必要とするという特徴がある。
　そして弁証法については、Aという意見とそれに反対するBという意見があり、それらを統合して両方の課題を取り入れたCという新しい意見を生み出す考え方のことだという説明をされることが多い。この説明はシンプルでわかりやすくはあるのだが、どうやってそれをするの？　という疑問が浮かんでも置いて行かれてしまうことが多い。せっかくなので、何回かに分けて弁証法という思考法について説明してみたいと思う。
　私が一番好きな三文字熟語は「弁証法」である。この弁証法での思考方法の1つに「否定の否定」という考え方がある。（ちなみに二番目に好きな三文字熟語は「業務用」です）
　今回は弁証法の中でも「否定の否定」に限って話をしてみたいと思う。

　あるAという意見があり、それをいったん否定し、反対のBという意見が出てきて、さらにそれに対する反論が出てきて、Bがさらに否定されてA’となる。AとA’は主張する内容は同じだが、Bという反論を乗り越えた後である分、A’の方が進歩した考え方だと言える。Aは自分の内に持っている「否定性」によって自らB、A’へと進んでいく。

　ここで弁証法の始祖の一人、ヘーゲルの言葉を引用してみよう。

「学の研究において大切なのは、概念の努力を自分で引き受けることである」
ヘーゲル『精神現象学』

　これが弁証法における「否定の否定」という考え方である。少しわかりにくいので冒頭の話と絡めてさらに考えてみる。
　少し前にバズっていたツイートで、日本の高校生が主催した平和について考えるイベントが紹介されいてた。日本の高校生がウクライナの避難民（“難民”ではないことが政治的には非常に重要らしい）の方に
「ウクライナに武器を送り続けていたら戦争が終わらないのではないか」
という意見を伝えた。そしてウクライナの避難民の方から
「武器がなければウクライナの市民が殺されてしまう」
という意見を返され、はじめに意見を言った日本の高校生はうまく言葉を返すことできず「戦争って一筋縄ではいかないんだな……」とこぼすしかなかった。
　この高校生を冷笑する意見が溢れかえっていたが、この高校生よりも自分は深く考えていると胸を張って答えられる人はどのくらいいるのだろう（ウクライナの避難民の方に無配慮な言葉をぶつけてしまったという点で批判されるというのならまだわかるが……）。
　弁証法はギリシア語では「ディアレクティケー」と言って「問答法」という意味である。意見が深まるとき、その意見は是非を問われ、必ず否定にぶつかる。
『ウクライナへの武器援助をやめれば戦闘は終わり平和になる』
という意見は、非常に素朴で最も直感的な意見だ。素朴というのは、かつての日本が強引に武器を作り続けて兵士を動員し続けたことで悲劇を長引かせた「先の大戦」についての教育から直接取り出されてくるであろう命題だという意味で、である。（これは悪い意味で言っているのではない。むしろ弁証法的には、この段階の議論を飛ばして複雑なことをいきなり考える方が邪道である）
　弁証法では、こうした素朴さのことを「直接的」とか「無媒介」のように言い表す。あらゆる命題はこの無媒介な状態から出発する。
　そして上記の意見に対して
『武器を失ったウクライナには平和は訪れない』
という否定意見がぶつけられる。この否定を乗り越えない限り、平和についてさらに深く考えることはできない。この否定を乗り越えた上で『○○をすれば平和になる』という意見を出さなければならない。この○○に入れるものは、人によって変わるだろう。
　ここから『ロシアの武器調達を阻止すれば平和になる』という意見が出てくるかもしれない。そのために世界はロシアに対して経済制裁を行っている。『ロシアとウクライナの両方が同時に戦闘をやめれば平和になる』という意見から、どこかの国が仲裁をして講和に持ち込むめばよいのではないかという姿勢が出てくる。
　これらの主張は、一度否定されたことによってはじめの主張より前進し、より現実に即したものになっている。こうした前進のことを「否定によって媒介されている」という言い方をする。
　ここで重要なのは、これらの否定意見は外からやってくるのではないということである。はじめの無媒介な意見の内部に既に否定が含まれている、という風に考える必要がある。少し分かりくいと思うのでさらに説明する。
　はじめに高校生が無媒介に直感した『ウクライナへの武器援助をやめれば戦争が終わり平和になる』に対して誰も否定意見を出さず、しかもこの高校生が世界の動きを決める権限を持っていたとしよう。そして自らの命題に従って国際社会を動かしたとしよう。するとどうなるか。武器援助を止められたウクライナは抵抗する力を次第に失っていき、ロシア軍によって市民は今以上の恐怖に陥れられるだろう。現実では、命題通りに平和が訪れることはない。つまり命題は実行されたことによって、命題がはじめから自分で持っている問題点によって否定されてしまう。

　抽象的すぎてよく意味が分からないかもしれない（私もよくわからない）。ヘーゲル研究者の樫山欽四郎氏は自著で

「内容が内容自らの自由性によって動くようにすることが求められねばならない。内容を内容自らの自己によって動くようにしてやること、そしてこの運動を観察すること、これが求められた態度である」
樫山欽四郎『ヘーゲル精神現象学の研究』

と解説している。独断と偏見と誇張を混じえて私の言葉に変換してみよう。
　何の問題点も持ち合わせていない命題など存在しない。どれだけ完璧な命題のつもりでも、必ず改善点がある。たとえ外部から反論されなかったとしても、命題自身の否定性（改善点を必ず持っている）という推進力によって、命題は常に前進しようとしている。その運動を止めてはならない。その運動を止めるのは、自分の意見は正しくこれ以上考える必要は無いと思い込む人間の傲慢さである。
　これが弁証法の世界観である。
「弁証法に限った話ではなくない？　ものを考えるときはそれくらいの謙虚な姿勢でいるべきだと考えるのが普通なのではないか？」と思った方。その通りです。
　今回の高校生に対して否定意見をぶつけていた人たちを見て思ったのは、それを否定している人たちはちゃんと自分の意見を自分なりに否定して媒介しているのか？　ということだ。
『ウクライナへの武器援助をやめれば平和になる』という命題は学校での歴史教育からそのまま直接取り出されたものだ。その意味でこれは無媒介な、まだ吟味されていない命題である。ウクライナの避難民の方と話をする前に、この命題について自分で吟味をすることがなかったという意味では、この高校生が批判されることもあり得るだろう。
　では、この高校生を批判する人たちはどんな命題を持っているのだろうか。
『ウクライナに寄付して平和に貢献するべき』
「ロシアに経済制裁をすれば平和になる』
『綺麗事で平和は実現されない』
　これらはどこかの学者やネット論客、あるいはTLのたくさんの意見からの引き写しではないのだろうか。
　引き写しが悪いと言っているのではない。
　他から引き写してきた意見を正しい者として外部から批判をぶつけてしまうのが良くないといっているのである。
　引き写しているということはその人にとっては無媒介な意見である。自分でその言葉を吟味し直したことがあるのだろうか。
　この高校生は今回のイベントでのやりとりを通して自分の意見を見直し、上で書いた3つの意見と同じ意見を持つようになるかもしれない。
　高校生の意見が、他から引き写してきた意見を正しいものとして外部から批判をぶつけている人たちと同じ意見になったとしても、一度否定を乗り越えた経験をその中に宿している分、そちらの方がより深い意見だと言えるだろう。
　この高校生はもはや、自分で否定した間違いに戻っていくことはない。
　たとえロシアに利益をもたらしてしまうような、平和から遠ざかるような情報操作やプロパガンダに惑わされそうになったとしても「ちょっと待って、ではウクライナの市民の安全はどうなる？」と必ず立ち止まることができるだろう。
　対して、外からの意見を引き写し続けている人たちはこれからも「誰を信じればよいのか？　何を信じればよいのか？」という戸惑いから自由になることはできない。高度な情報戦争の中で右往左往することになるであろう。
　ヘーゲルが(樫山欽四郎の解説曰く)「内容を内容自らの自己によって動くようにして」、「そしてこの運動を観察する」という態度を求めている理由がここにある。
　競技ディベートでは、相手の主張の問題点を指摘することと自分の主張を説明することとを明確に区別している。弁証法では特に前者を、真理の探究の方法として重視しているということができる。
　外部からただ別の意見をぶつけて、元々あった前提も考慮もすべて無に帰してしまうような否定は、相手をやっつけることを重視するレスバトルでは有効なのかもしれないが、真理を探究する手段としての弁証法的な観点からすると全く役に立たないものであると言える。

　皆さんも一度、自分の意見はどこから来たものなのか、どれだけ自分で吟味してみた意見なのか、振り返ってみてはいかがでしょうか。
　以上、弁証法オタクの丸井零でした。
　キーワードは「無媒介」と「否定の否定」です。


** 012_Twitter断食一週間目、ネットに依存する精神の動きについての観察結果とその分析 
　ツイッターを封印してからちょうど一週間が経とうとしている。だいたいこういう記録は、ツイッターを封印したことでこんなことができたとか、こんないいことがあったとかを報告できることが「成功」になると思う。そういう意味では今回のツイッター断食、および各種SNSサービスの封印は明らかに失敗してしまった。
　SNSを封印して3日ほど経ったあたりから、禁断症状のようなものが出始めた。ツイッター以外で、とにかくなんでもいいから情報刺激が欲しくなった。そして私は、ブラウザを開いて昔はよく見ていた2chのまとめサイトなどを徘徊した。この結果、ツイッターをしないことで得られたはずの、「有効活用するはずだった時間」はすべてネットの海に霧散してしまった。非常にもったいないことをした。

　一応言い訳をするなら、今回私はツイッターをやめること自体を目的としていたわけではない。闇雲に、衝動的な変身願望に突き動かされてツイッターやSNS、動画サービスなどを封印して成功したことがあっただろうか。、ほとんどの人は成功しないと思う。私も両手の指で数え切れないくらいにはSNSの封印にチャレンジしていた。そしてその全てに失敗した。
　今回は、なぜSNSに依存してしまうのか、そもそも依存することによって何を失っているのか。逆にプラスの影響はないのか。SNSのどの要素が依存性を持っているのか、などを自分の心身で実験してみたかった。

　ここからは、ツイッターなどの各種サービスを封印しながら、自分で自分の精神について考えてみて思ったことを書く。私には倫理学や脳科学の素養はない。だからすべての人に通ずるものを引き出すことができたとは思わない。　また、私の精神は他の人に比べて弱い。だから私の精神で起こっているであろう情けない現象は、他の人には起こっていない可能性も十分にある。これから書く記述を見て、自分の普段の行動を否定されていると感じた場合、つまりそんな低俗な考えでSNSを触っているのではないと思った人は、私より強い精神を持っている。ここに書いていることは関係ないと考えていただいて構わない。
だが、私と同じくらい精神が弱く外部の影響を受けやすい人は、もしかしたら参考にしてもらえるかもしれない。私はそんな弱くて、そして苦しんでいる人のために書いてみようと思う。

　ツイッターから離れることがそんなに大事なことなのだろうか。そういう疑問も浮かぶ。新しい情報は得られるし、考えるべきテーマもたくさん発掘できる。素敵な創作者の方々と交流することもできる。それでも私はツイッターの負の側面のほうがここ数年は特に強くなっているのではないかと感じている。

　実際のところ、SNS依存とはなんであろうか。というより、私は何から逃れたくて自分をSNS依存であると断定したのであろうか。もっとわかりやすいのは、ツイッターの見すぎで他のことに時間を使えなくなってしまったということだ。ではどんな使い方をしてそうなっているのだろうか。FFとのやりとりに没頭しているわけではない。延々とツイートをし続けているというわけでもない。私がやっているのは「ホーム」をひたすら更新することと、特定のワードで検索してそれについての意見を探し続けるというものだ。

　ツイッターの情報はトゲトゲしているという表現を以前した。これは少し間違っているのかもしれない。正しくは、ツイッターの情報は私の精神をトゲトゲさせるのかもしれない。私は自分のトゲによって傷ついて疲弊しているような気がする。
　私は何かのニュースや主張を見て、「これは間違っている！」と判断する瞬間に起こる精神的現象に依存している。同時に「この意見は正しい！」と判断するときの精神的現象にも依存している。どういうことか順番に説明したい。
　まず、私は「間違い」を探す。それは誰かの不祥事かもしれないし、問題発言かもしれないし、どこかの企業が行った間違ったプロモーションかもしれない。あるいは偶然バズってしまったただの一般人のツイートかもしれない。とにかくそれに対して私は「間違い」を見出す。
　実験用ラットがスイッチを押すかのように、SNSや動画サービスのホームやおすすめを更新し続けていれば、それは簡単に見つけることができる。そしてこの「間違い」に複数寄せられている他の人の「正しい」意見を見て快感に似た刺激を得ている。
　このとき私は、「間違い」を見て自分の意見をまず考えて自分の意見を確立するようなことはしない。自分の立場を明確にしてから寄せられている他の人の意見を確認するのではない。そうではなく、「間違い」を見た瞬間に私は直感的に不快感を抱く。なぜ不快感を抱くのかを自分で考えるのではなく、寄せられている他人の意見からその理由を得ようとする。そしてそれが不快感の理由たりうるものであればその時「正しい」と感じる。
　このとき、それが本当に正しいのかどうかは関係がない、というより知りようがない。社会的に正しいと言われる意見で「正しい」と感じてその刺激に依存することもあれば、社会的には間違っていると判断されるであろう意見を見て「正しい」と感じてその刺激に依存することもある。これは内容の話ではない。脳内で何が起こっているかの話である。

ツイッターを封印したとき、私はブラウザで2chのまとめサイトを巡回するようになった。そうした2chサイトはよくないと思いそれらも閲覧制限をかけた。その結果としていくつか本を読んだりアニメを見たりと、文化的な楽しみに時間を使うことができた。だがその後、その本やアニメの感想をネット上に探し求めた。ツイッターをわざわざブラウザから見たり、アマゾンや読書メータのレビューなども漁った。結局私は時間を有意義に使えたのか使えなかったのか、よくわからない状態になってしまった。
　このことから、上の説明をもう少し拡張することができるかもしれない。
　私は何かを見たとき「直感的な感想」を抱く。ここでいう感想とは、感動したとか不快だとか傷ついたとか面白いとか、とにかく言葉で理論的に説明するまえの心の動きのことを指している。辞書的な意味での感想よりも広い意味で使っている。
　この直感的な感想がなぜ起こっているのかについての「説明」を求める。そして、より納得できる説明を求めてひたすらそれを探し続ける。ここで重要なのは、私の中に自分なりの説明があり、それとぴったり合うものを探しているわけではないということだ。私は説明を持っていない。持つ前から自分にあう説明を外部に求める。そして私はいつの間にか、自分で説明を用意していなかったことを忘れてしまう。
　自分では説明を用意していないのに、自分の説明に合う他の人の説明を探し求める。自分では説明を用意していないが、私はどこから持ち込んできたのか既に自分のなりの説明を手に持っている。それが元から自分のものだったのか、外から持ってきたものそのままなのか、自分なりにアレンジしたものなのか、外から持ってきないろいろなものが合体して起源がわからなくなってしまっているのか、それを知ることはできない。いつそれを手に持ったのかわからないし、これから先別の説明とすり替えられたとしてもそのことに気づくことはできない。
　わかることは、私はそんな「戸籍のない説明」とぴったり合う他の説明を常に探し求めているということだ。数学で習う双曲線のグラフが漸近線とどこまでいっても延々に交わることがないのと同じように、この探し求めは終わることがない。

　この「感想」を最初に説明した「間違い」に、そして「説明」を「正しい」に置き換えることもできる。
　私は誰かの不祥事や問題発言やツイートに対して、それは間違いであるという「感想」を抱く。繰り返しになるが、こうした間違いはツイッターのホームを更新し続けたり特定のワードで検索をかければ簡単に見つけることができる。だが私はその感想を抱く理由を自分で説明することはない。それをする前から、私は自分が正しいと感じるために他の人の「説明」を求め始める。引用リツートやリプライ欄をタップすればそうした説明が満ち溢れているだろう。それでも満足できなければまた検索すればよい。
　月並な表現になるが、これまで述べたことを完結表すなら、私は自分の意見がわからないまま自分を納得させてくれる説明を探し続けるのだ。だが、そのプレセスは思いの外入り組んでいるため簡単に抜け出すことはできない。

　こうした精神の働きがあるから、SNSは怖いのだ……という話で結論を出そうと思っていた。

　だがよく考えると、人は自分で言語化できない感想を抱いてしまったとき、こうした上記のような対応をして救われることがある。
　新しい説明、新しい概念と出会うことで世界が開けるときもある。あるいはそれこそが「勉強」と呼ばれる行為かもしれないのだ。自分が受け取るすべてのものを自分の力で言語化することなどできない。私は他者の正しいと思える意見を吸収していきながら、少しずつ世界を広げていく。だからそれ自体は悪いことではないのだと思う。
　人が生きて成長していく限り、つまり世界を広げていく方向性を持っている限り、SNSへの依存を完全になくすことはできないのだと思う。生物が生きるために進化の過程で獲得した性質が、まったく別の病気を呼び込んでしまうのと同じように、人が成長するための能力そのものが、SNSへの依存を呼び込んでしまっているのだと思う。


2023年2月23日

** 【未投稿】書きたいことを集める場所
*** 思想の棚卸し


*** 対異形バトル百合と特攻の歴史、そして実存主義について
自分が何を好きなのか、何を書きたいのか、何を表現したいと思っているのか、最近わからなくなってきた。自分がこれまでどのような百合作品に魅せられてきて、どういったテーマに心を揺さぶられたのか、振り返ってみることにした。
